# Data Structures, Functions, NumPy & Pandas — Assignment

This notebook answers all questions from the assignment doc, organized into:

- **Section A:** Data Structures & Control Structures
- **Section B:** NumPy
- **Section C:** Exploring Pandas

Each question has a short markdown explanation followed by clean, commented Python code, executed with its output shown below the cell.

## Setup

Import the libraries used across the notebook.

In [1]:
# Import required libraries
import numpy as np
import pandas as pd

# Fix the random seed so random outputs are reproducible on every run
np.random.seed(42)

# Section A: Data Structures & Control Structures

## Q1. List Operations

Create a list of 5 integers and demonstrate: `append`, `extend`, `insert`, `remove`, `pop`, `clear`, `index`, `count`, `sort`, and `reverse`.

Each operation's effect is printed immediately after it runs so the change is visible step by step.

In [2]:
# Start with a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# append(): adds a single element to the end of the list
numbers.append(60)
print("After append(60):", numbers)

# extend(): adds all elements of another iterable to the end of the list
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# insert(): inserts an element at a specific index
numbers.insert(2, 25)  # insert 25 at index 2
print("After insert(2, 25):", numbers)

# remove(): removes the first matching value from the list
numbers.remove(25)
print("After remove(25):", numbers)

# pop(): removes and returns the element at the given index (last element if no index given)
popped_value = numbers.pop()
print(f"After pop() -> removed {popped_value}:", numbers)

# index(): returns the index of the first occurrence of a value
position = numbers.index(30)
print(f"index(30) -> found at position {position}")

# count(): counts how many times a value appears in the list
numbers.append(30)  # add a duplicate so count() has something meaningful to show
print("List after adding a duplicate 30:", numbers)
occurrences = numbers.count(30)
print(f"count(30) -> {occurrences} occurrence(s)")

# sort(): sorts the list in place, in ascending order by default
numbers.sort()
print("After sort():", numbers)

# reverse(): reverses the order of elements in place
numbers.reverse()
print("After reverse():", numbers)

# clear(): removes all elements from the list
numbers.clear()
print("After clear():", numbers)

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(25): [10, 20, 30, 40, 50, 60, 70, 80]
After pop() -> removed 80: [10, 20, 30, 40, 50, 60, 70]
index(30) -> found at position 2
List after adding a duplicate 30: [10, 20, 30, 40, 50, 60, 70, 30]
count(30) -> 2 occurrence(s)
After sort(): [10, 20, 30, 30, 40, 50, 60, 70]
After reverse(): [70, 60, 50, 40, 30, 30, 20, 10]
After clear(): []


## Q2. Tuples Are Immutable

Create a tuple of 3 student names and try to change the second name.

**Explanation:** Tuples are *immutable* — once created, their elements cannot be reassigned. Attempting `tuple[index] = value` raises a `TypeError`, unlike a list where item assignment is allowed. This immutability is why tuples are used for fixed collections of data that shouldn't change (e.g., coordinates, records).

In [3]:
# A tuple of 3 student names
students = ("Alice", "Bob", "Charlie")
print("Original tuple:", students)

# Try changing the second name (index 1) and catch the resulting error
try:
    students[1] = "Bobby"
except TypeError as error:
    print(f"Error occurred: {error}")
    print("Explanation: tuples are immutable, so individual elements cannot be reassigned "
          "after the tuple is created.")

Original tuple: ('Alice', 'Bob', 'Charlie')
Error occurred: 'tuple' object does not support item assignment
Explanation: tuples are immutable, so individual elements cannot be reassigned after the tuple is created.


## Q3. Sets Remove Duplicates

Create a set of integers that includes duplicate values and print it.

**Explanation:** A `set` in Python only stores **unique** elements. When duplicate values are supplied, Python automatically discards the repeats, and the set also does not preserve insertion order (elements are stored based on their hash for fast membership testing).

In [4]:
# Create a set with intentional duplicate values
numbers_set = {1, 2, 2, 3, 4, 4, 4, 5}
print("Set (duplicates removed automatically):", numbers_set)

print("Explanation: even though the value 2 was written twice and 4 was written three "
      "times, the set keeps only one copy of each because sets only store unique elements.")

Set (duplicates removed automatically): {1, 2, 3, 4, 5}
Explanation: even though the value 2 was written twice and 4 was written three times, the set keeps only one copy of each because sets only store unique elements.


## Q4. Dictionary Operations

Create a dictionary with keys `'name'`, `'age'`, `'city'`, then update the age and add a new `'email'` key.

In [5]:
# Create the initial dictionary
person = {"name": "Priya", "age": 25, "city": "Hyderabad"}
print("Original dictionary:", person)

# Update the existing 'age' key
person["age"] = 26
print("After updating age:", person)

# Add a new key 'email'
person["email"] = "priya@example.com"
print("Final dictionary:", person)

Original dictionary: {'name': 'Priya', 'age': 25, 'city': 'Hyderabad'}
After updating age: {'name': 'Priya', 'age': 26, 'city': 'Hyderabad'}
Final dictionary: {'name': 'Priya', 'age': 26, 'city': 'Hyderabad', 'email': 'priya@example.com'}


## Q5. Voting Eligibility Check

Take a person's age and check whether they are eligible to vote (age ≥ 18).

In [6]:
# Age of the person (change this value to test different cases)
age = 20

# Check voting eligibility
if age >= 18:
    print(f"Age {age}: Eligible to vote.")
else:
    print(f"Age {age}: Not eligible to vote.")

Age 20: Eligible to vote.


## Q6. Grade Calculator

Given a `marks` variable, print the grade based on:
- 90 and above → `'A'`
- 75–89 → `'B'`
- 50–74 → `'C'`
- Below 50 → `'Fail'`

In [7]:
# Marks scored by the student (change this value to test different grade bands)
marks = 82

# Determine the grade using if / elif / else
if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "Fail"

print(f"Marks: {marks} -> Grade: {grade}")

Marks: 82 -> Grade: B


## Q7. Positive / Even / Zero / Negative Check

Given a number, check whether it is positive (and if so, whether it is also even). If it is not positive, report whether it is zero or negative.

In [8]:
# Number to check (change this value to test different cases)
number = -6

if number > 0:
    print(f"{number} is positive.")
    if number % 2 == 0:
        print(f"{number} is also even.")
    else:
        print(f"{number} is odd.")
elif number == 0:
    print(f"{number} is zero.")
else:
    print(f"{number} is negative.")

-6 is negative.


# Section B: NumPy

## Q8. Creating Arrays

Create:
- A scalar using `np.array(5)`
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [9]:
# A 0-dimensional scalar array
scalar = np.array(5)
print("Scalar array:", scalar)
print("Scalar ndim:", scalar.ndim)

# A 1D array containing values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D array:", array_1d)
print("1D array shape:", array_1d.shape)

# A 2D array (2 rows x 3 columns) with values 10 to 60 in steps of 10
# arange(10, 70, 10) generates [10, 20, 30, 40, 50, 60], then reshape to 2x3
array_2d = np.arange(10, 70, 10).reshape(2, 3)
print("\n2D array (2x3):\n", array_2d)
print("2D array shape:", array_2d.shape)

Scalar array: 5
Scalar ndim: 0

1D array: [1 2 3 4 5]
1D array shape: (5,)

2D array (2x3):
 [[10 20 30]
 [40 50 60]]
2D array shape: (2, 3)


## Q9. Random Integer Array

Generate a 4x4 NumPy array of random integers between 0 and 100 using `np.random.randint()`.

(The random seed set in the Setup cell makes this reproducible across runs.)

In [10]:
# Generate a 4x4 array of random integers in the range [0, 100)
random_array = np.random.randint(0, 100, size=(4, 4))
print("4x4 random integer array:\n", random_array)

4x4 random integer array:
 [[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]


## Q10. 2D NumPy Array to Pandas DataFrame

Create a 2D NumPy array of shape (3x3), convert it into a Pandas DataFrame, and add column names `'A'`, `'B'`, `'C'`.

In [11]:
# Create a 3x3 array of random integers
array_3x3 = np.random.randint(1, 50, size=(3, 3))
print("3x3 NumPy array:\n", array_3x3)

# Convert it into a Pandas DataFrame with named columns
df_from_array = pd.DataFrame(array_3x3, columns=["A", "B", "C"])
print("\nAs a Pandas DataFrame:")
df_from_array

3x3 NumPy array:
 [[ 2 24 44]
 [30 38  2]
 [21 33 12]]

As a Pandas DataFrame:


    A   B   C
0   2  24  44
1  30  38   2
2  21  33  12

# Section C: Exploring Pandas

## Q11. Building and Cleaning a DataFrame

Create a small DataFrame manually with 10 rows and columns `'Name'`, `'Age'`, `'City'`, and `'Salary'`.
A couple of missing `Salary` values and one duplicate row are included on purpose so that the
cleaning steps below (filling missing values, dropping duplicates) have something real to act on.

Then:
- Use `.info()` and `.describe()`
- Select the `'Name'` and `'City'` columns
- Drop the `'City'` column
- Fill missing values in `'Salary'` with the column mean
- Remove duplicate rows

In [12]:
# Manually created data: 10 rows, with one duplicate row (rows for "Ivan")
# and a couple of missing Salary values (represented with np.nan) to make the
# cleaning steps meaningful.
data = {
    "Name":   ["Aditi", "Rahul", "Meera", "Karan", "Sara",
               "Ivan",  "Ivan",  "Neha",  "Vikram", "Farah"],
    "Age":    [23, 35, 29, 41, 27, 33, 33, 24, 38, 30],
    "City":   ["Hyderabad", "Delhi", "Mumbai", "Bengaluru", "Chennai",
               "Pune", "Pune", "Kolkata", "Ahmedabad", "Jaipur"],
    "Salary": [45000, 62000, np.nan, 78000, 51000,
               58000, 58000, np.nan, 71000, 49000],
}

df = pd.DataFrame(data)
print("Full DataFrame:")
df

Full DataFrame:


     Name  Age       City   Salary
0   Aditi   23  Hyderabad  45000.0
1   Rahul   35      Delhi  62000.0
2   Meera   29     Mumbai      NaN
3   Karan   41  Bengaluru  78000.0
4    Sara   27    Chennai  51000.0
5    Ivan   33       Pune  58000.0
6    Ivan   33       Pune  58000.0
7    Neha   24    Kolkata      NaN
8  Vikram   38  Ahmedabad  71000.0
9   Farah   30     Jaipur  49000.0

In [13]:
# .info() gives column dtypes, non-null counts, and memory usage
print("DataFrame info:")
df.info()

DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     str    
 1   Age     10 non-null     int64  
 2   City    10 non-null     str    
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 452.0 bytes


In [14]:
# .describe() gives summary statistics for the numeric columns
print("Summary statistics:")
df.describe()

Summary statistics:


             Age        Salary
count  10.000000      8.000000
mean   31.300000  59000.000000
std     5.831905  11186.726829
min    23.000000  45000.000000
25%    27.500000  50500.000000
50%    31.500000  58000.000000
75%    34.500000  64250.000000
max    41.000000  78000.000000

In [15]:
# Select only the 'Name' and 'City' columns
name_city = df[["Name", "City"]]
print("Name and City columns:")
name_city

Name and City columns:


     Name       City
0   Aditi  Hyderabad
1   Rahul      Delhi
2   Meera     Mumbai
3   Karan  Bengaluru
4    Sara    Chennai
5    Ivan       Pune
6    Ivan       Pune
7    Neha    Kolkata
8  Vikram  Ahmedabad
9   Farah     Jaipur

In [16]:
# Drop the 'City' column (axis=1 means we're dropping a column, not a row)
df_no_city = df.drop(columns=["City"])
print("DataFrame after dropping 'City':")
df_no_city

DataFrame after dropping 'City':


     Name  Age   Salary
0   Aditi   23  45000.0
1   Rahul   35  62000.0
2   Meera   29      NaN
3   Karan   41  78000.0
4    Sara   27  51000.0
5    Ivan   33  58000.0
6    Ivan   33  58000.0
7    Neha   24      NaN
8  Vikram   38  71000.0
9   Farah   30  49000.0

In [17]:
# Fill missing values in 'Salary' with the column's mean
salary_mean = df["Salary"].mean()
print(f"Mean salary (ignoring missing values): {salary_mean:.2f}")

df["Salary"] = df["Salary"].fillna(salary_mean)
print("\nDataFrame after filling missing Salary values:")
df

Mean salary (ignoring missing values): 59000.00

DataFrame after filling missing Salary values:


     Name  Age       City   Salary
0   Aditi   23  Hyderabad  45000.0
1   Rahul   35      Delhi  62000.0
2   Meera   29     Mumbai  59000.0
3   Karan   41  Bengaluru  78000.0
4    Sara   27    Chennai  51000.0
5    Ivan   33       Pune  58000.0
6    Ivan   33       Pune  58000.0
7    Neha   24    Kolkata  59000.0
8  Vikram   38  Ahmedabad  71000.0
9   Farah   30     Jaipur  49000.0

In [18]:
# Remove duplicate rows (the two identical "Ivan" rows collapse into one)
print(f"Row count before removing duplicates: {len(df)}")

df_deduped = df.drop_duplicates()

print(f"Row count after removing duplicates: {len(df_deduped)}")
print("\nFinal cleaned DataFrame:")
df_deduped

Row count before removing duplicates: 10
Row count after removing duplicates: 9

Final cleaned DataFrame:


     Name  Age       City   Salary
0   Aditi   23  Hyderabad  45000.0
1   Rahul   35      Delhi  62000.0
2   Meera   29     Mumbai  59000.0
3   Karan   41  Bengaluru  78000.0
4    Sara   27    Chennai  51000.0
5    Ivan   33       Pune  58000.0
7    Neha   24    Kolkata  59000.0
8  Vikram   38  Ahmedabad  71000.0
9   Farah   30     Jaipur  49000.0